### ISSUE TITLE
MALT10k_groundTruth.csv data is missing

### ISSUE THREAD

**Issue by archi456** [deeplearner87/UMINT#1]
When I am trying to run MALT10K_UMINT.ipynb file , I am not able to find MALT10k_groundTruth.csv data . In the given dataset link , there is no groundtruth data .

**Comment by deeplearner87** [comment]
You can download the ground truth information for MALT10k from the data source (check the Resource availability section of the cited manuscript) mentioned in Table 1 (page 5) of the manuscript.
